- name: Update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install telegraf
  shell: |
    curl -s https://repos.influxdata.com/influxdata-archive.key > influxdata-archive.key
    echo '943666881a1b8d9b849b74caebf02d3465d6beb716510d86a39f6c8e8dac7515 influxdata-archive.key' | sha256sum -c && cat influxdata-archive.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/influxdata-archive.gpg > /dev/null
    echo 'deb [signed-by=/etc/apt/trusted.gpg.d/influxdata-archive.gpg] https://repos.influxdata.com/debian stable main' | sudo tee /etc/apt/sources.list.d/influxdata.list

- name: Update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install packages
  apt:
    pkg:
      - libsecret-tools
      - novnc
      - telegraf
    state: present

- name: create telegraf config directory
  file:
    path: /etc/telegraf/telegraf.d
    state: directory

- name: copy base telegraf output plugin
  copy:
    src: templates/telegraf.output.conf
    dest: /etc/telegraf/telegraf.d/telegraf.output.conf
    owner: root
    group: root
    mode: 0644

- name: enable and start telegraf
  systemd:
    name: telegraf
    enabled: yes
    state: restarted

- name: create resolved directory
  file:
    path: /etc/systemd/resolved.conf.d
    state: directory

- name: Add cluster DNS configuration
  copy:
    src: templates/dns_servers.conf
    dest: /etc/systemd/resolved.conf.d/dns_servers.conf
    owner: root
    group: root
    mode: 0644

- name: restart resolved
  systemd:
    name: systemd-resolved
    enabled: yes
    state: restarted

- name: Ensure automatic login is set
  copy:
    src: templates/gdm.custom.conf
    dest: /etc/gdm3/custom.conf
    owner: root
    group: root
    mode: 0644

- name: Copy xstartup
  copy:
    src: templates/vncconfigs/xstartup
    dest: /home/ubuntu/.vnc/xstartup
    owner: ubuntu
    group: ubuntu
    mode: a+x

- name: Enable and start vncserver
  become: true
  become_user: ubuntu
  systemd:
    name: gnome-remote-desktop
    enabled: yes
    state: restarted
    scope: user

- name: Enable vnc shenanigans
  become: true
  become_user: ubuntu
  shell: |
    grdctl vnc enable
    gsettings set org.gnome.desktop.screensaver lock-enabled false
    gsettings set org.gnome.desktop.session idle-delay 0

- name: Set vnc password
  copy:
    src: templates/vncconfigs/remotedesktop.credentials
    dest: /home/ubuntu/.local/share/keyrings/login.keyring # This stores the unlocked variant so we don't have to change passwords every login
    owner: ubuntu
    group: ubuntu
    mode: 0600

- name: Create novnc service
  copy:
    src: templates/vncconfigs/novnc.service
    dest: /etc/systemd/system/novnc.service
    owner: root
    group: root
    mode: 0644

- name: enable novnc
  systemd:
    name: novnc
    enabled: yes
    state: restarted

- name: Turn swap off
  shell: |
    swapoff -a
    sed -i '/ swap / s/^/#/' /etc/fstab