apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitea
  namespace: shared-services
spec:
  selector:
    matchLabels:
      app: gitea
  serviceName: "gitea"
  replicas: 1
  template:
    metadata:
      labels:
        app: gitea
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: gitea
          image: gitea/gitea:1.21.4
          ports:
            - containerPort: 3000
              name: web
            - containerPort: 22
              name: ssh
          volumeMounts:
            - name: config
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: mayastor-3-rv
        resources:
          requests:
            storage: 50Gi
