---
apiVersion: v1
kind: Service
metadata:
  name: gitea
  namespace: shared-services 
spec:
  ports:
  - port: 22 
    name: ssh
    protocol: TCP
    targetPort: 22
  - port: 80
    name: web
    protocol: TCP
    targetPort: 3000
  selector:
    app: gitea
  type: LoadBalancer
