apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: shared-services
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.128.101
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: grafana
  type: LoadBalancer