apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdb
  namespace: shared-services
spec:
  selector:
    matchLabels:
      app: influxdb 
  serviceName: "influxdb"
  replicas: 1
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: influxdb
        image: influxdb:2.7.5
        env:
        - name: DOCKER_INFLUXDB_INIT_MODE
          value: "setup"
        - name: DOCKER_INFLUXDB_INIT_USERNAME
          value: "admin"
        - name: DOCKER_INFLUXDB_INIT_BUCKET
          value: "lessons"
        - name: DOCKER_INFLUXDB_INIT_PASSWORD
          value: "adminadmin"
        - name: DOCKER_INFLUXDB_INIT_ORG
          value: "lessons"
        - name: DOCKER_INFLUXDB_INIT_RETENTION
          value: "4w"
        - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
          value: "adminadmin"
        ports:
        - containerPort: 8086
        volumeMounts:
        - name: config
          mountPath: /var/lib/influxdb2
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: mayastor-3-rv
      resources:
        requests:
          storage: 100Gi