---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: shared-services 
spec:
  ports:
  - port: 80
    name: web
    protocol: TCP
    targetPort: 8080
  selector:
    app: jenkins
  type: LoadBalancer
