apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: registry
  namespace: shared-services
spec:
  selector:
    matchLabels:
      app: registry 
  serviceName: "registry"
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: registry
        image: registry:2.8.3
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: config
          mountPath: /var/lib/registry
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: mayastor-3-rv
      resources:
        requests:
          storage: 50Gi