---
apiVersion: v1
kind: Namespace
metadata:
  name: philip-almueti
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-lesson
  namespace: philip-almueti
  labels:
    app: sample-lesson
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-lesson
  template:
    metadata:
      labels:
        app: sample-lesson
    spec:
      containers:
        - name: sample-lesson
          image: registry.shared-services/sample-lesson2/sample-lesson2
          ports:
            - containerPort: 3389
          imagePullPolicy: Always
          volumeMounts:
            - name: scores-config
              mountPath: /etc/telegraf/telegraf.d/scores.conf
              subPath: scores.conf
            - name: global-config
              mountPath: /etc/telegraf/telegraf.d/global.conf
              subPath: global.conf
      volumes:
        - name: scores-config
          configMap:
            name: scores-config
            items:
              - key: scores.conf
                path: scores.conf
        - name: global-config
          configMap:
            name: global-config
            items:
              - key: global.conf
                path: global.conf
---
apiVersion: v1
kind: Service
metadata:
  name: philip-almueti
  namespace: philip-almueti
spec:
  ports:
    - name: rdp
      port: 3389
      targetPort: 3389
  selector:
    app: sample-lesson
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scores-config
  namespace: philip-almueti
data:
  scores.conf: |
    [[inputs.exec]]
      commands = ['/bin/bash -c "if cat /config/.bash_history | grep \"id paarthurnax\";then echo \"12\"; else echo \"0\";fi"']
      data_format = "value"
      data_type = "integer"
      name_override = "paarthurnax_identified"
      tags = {type = "score"}
    [[inputs.exec]]
      commands = ['/bin/bash -c "if cat /etc/passwd | grep -q ballen;then echo \"0\"; else echo \"5\";fi"']
      data_format = "value"
      data_type = "integer"
      name_override = "ballen_removed"
      tags = {type = "score"}
    [[inputs.exec]]
      commands = ['/bin/bash -c "if cat /etc/passwd | grep -q sheogorath;then echo \"0\"; else echo \"5\";fi"']
      data_format = "value"
      data_type = "integer"
      name_override = "sheogorath_removed"
      tags = {type = "score"}
    [[inputs.exec]]
      commands = ['/bin/bash -c "if id ulfric | grep -q root;then echo \"0\"; else echo \"5\";fi"']
      data_format = "value"
      data_type = "integer"
      name_override = "ulfric_not_admin"
      tags = {type = "score"}
    [[inputs.exec]]
      commands = ['/bin/bash -c "if cat /etc/shadow | grep -q papAq5PwY/QQM;then echo \"0\"; else echo \"5\";fi"']
      data_format = "value"
      data_type = "integer"
      name_override = "esbern_insecure"
      tags = {type = "score"}
    [[inputs.exec]]
      commands = ['/bin/bash -c "if cat /etc/passwd | grep -q belethor;then echo \"0\"; else echo \"5\";fi"']
      data_format = "value"
      data_type = "integer"
      name_override = "belethor_not_found"
      tags = {type = "score"}
