---
- hosts: linux
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/sbin"
  vars:
    k8s_version: "1.29" # Latest version of k8s at the time of writing
    k8s_cidr: "10.244.0.0/16" # This is the default CIDR for flannel
    metallb_range: "192.168.128.100-192.168.128.199"
    registry_ip: "192.168.128.100"
  tasks:
    - name: Setup k8s dependencies
      include_tasks: tasks/establish-cluster.yml
    - name: Setup k8s shared services
      when: inventory_hostname in groups['controllers']
      include_tasks: tasks/deploy-shared-services.yml
