#############################################
# Setup with shared services - these are services that are resources shared by users, not necessarily part of the core infrastructure
#############################################

- name: Deploy namespace
  kubernetes.core.k8s:
    state: present
    name: shared-services
    api_version: v1
    kind: Namespace

- name: Deploy influxDB pods
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'deployments/influxdb-deployment.yml') | from_yaml }}"

- name: Deploy influxDB service
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'deployments/influxdb-service.yml') | from_yaml }}"

- name: Deploy registry pods
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'deployments/registry-deployment.yml') | from_yaml }}"

- name: Deploy registry service
  kubernetes.core.k8s:
    state: present
    template: registry-service.yml.j2

#- name: Deploy kubeshark
#  kubernetes.core.k8s:
#    state: present
#    src: deployments/kubeshark.yml
#
#- name: Deploy kubevirt
#  kubernetes.core.k8s:
#    state: present
#    src: deployments/kubevirt.yml

- name: Deploy grafana pods
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'deployments/grafana-deployment.yml') | from_yaml }}"

- name: Deploy grafana service
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'deployments/grafana-service.yml') | from_yaml }}"

- name: Deploy jenkins pods
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'deployments/jenkins-deployment.yml') | from_yaml }}"

- name: Deploy jenkins service
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'deployments/jenkins-service.yml') | from_yaml }}"

- name: Deploy jenkins configmap
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'deployments/jenkins-configmap.yml') | from_yaml }}"

- name: Deploy gitea pods
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'deployments/gitea-deployment.yml') | from_yaml }}"

- name: Deploy gitea service
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'deployments/gitea-service.yml') | from_yaml }}"
#- name: Deploy grafana templates
#  kubernetes.core.k8s:
#    state: present
#    src: grafana-dashboards.yml
#- name: Deploy dummy jenkinsauth secret for dashboard
#  kubernetes.core.k8s:
#    state: present
#    api_version: v1
#    kind: Secret
#    name: jenkinsauth
#    namespace: shared-services
#    # TODO: Fix this
#    data:
#      JENKINSAUTH: "foobar"

#- name: Deploy dummy gitea ssh secret for dashboard
#  kubernetes.core.k8s:
#    state: present
#    api_version: v1
#    kind: Secret
#    name: giteassh
#    namespace: shared-services
#    data:
#      id_rsa: "foobar"

- name: Deploy dashboard pods
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'deployments/gitea-deployment.yml') | from_yaml }}"

- name: Deploy dashboard service
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'deployments/gitea-service.yml') | from_yaml }}"

- name: Deploy dashboard ClusterRole
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'deployments/dashboard-cr.yml') | from_yaml }}"

- name: Deploy dashboard ClusterRoleBinding
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'deployments/dashboard-crb.yml') | from_yaml }}"

- name: Deploy dashboard Service Account
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'deployments/dashboard-sa.yml') | from_yaml }}"

- name: Deploy dashboard SA Secret
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'deployments/dashboard-secret.yml') | from_yaml }}"
