- name: Add apt_key
  block:
    - name: K8S Repo
      get_url: 
        url: https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/Release.key
        dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc

    - name: Add repository
      apt_repository:
        filename: kubernetes.list
        repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/ /
        state: present

- name: Install/Update k8s packages
  apt:
    pkg:
      - kubelet={{ k8s_version }}.1-1.1
      - kubeadm={{ k8s_version }}.1-1.1
      - kubectl={{ k8s_version }}.1-1.1
    state: present

- name: Hold kubelet
  dpkg_selections:
    name: kubelet
    selection: hold

- name: Hold kubeadm
  dpkg_selections:
    name: kubeadm
    selection: hold

- name: Hold kubectl
  dpkg_selections:
    name: kubectl
    selection: hold

- name: Disable swap
  command: /usr/sbin/swapoff -a

- name: Update fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '^(UUID=.*swap.*)'
    line: '# \1'
    backrefs: yes
    state: present

#- name: If node is controller, check if cluster is established and create cluster otherwise
#
#- name: If node is worker, check if cluster is established and join cluster otherwise
#
#- name: Copy admin kubeconfig locally
